/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shortTermCourseManagement;

import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class TempFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form TempFrame1
     */
    public JButton b2;
    public Course tempc;
    public JTextField facdept;
    public JTextField facnam;
    public JTextField facadd;
    public JTextField facemail;
    public JTextField facmob;
    public TempFrame1(JButton b2,Course tempc) {
        this.tempc=tempc;
        this.b2=b2;
        tempframe1();
    }
    public void tempframe1()
    {
        Container c=getContentPane();
        c.setLayout(new GridLayout(0,2));
        c.add(new JLabel("Faculty deptt"));
        facdept=new JTextField();
        c.add(facdept);
        c.add(new JLabel("Faculty Name"));
        facnam=new JTextField();
        c.add(facnam);
        c.add(new JLabel("Faculty Address"));
        facadd=new JTextField();
        c.add(facadd);
        c.add(new JLabel("Faculty email"));
        facemail=new JTextField();
        c.add(facemail);
        c.add(new JLabel("Faculty Mobile"));
        facmob=new JTextField();
        c.add(facmob);
        c.add(new JPanel());
        c.add(b2);
        //JOptionPane.showMessageDialog(null,"Faculty Added","Added",JOptionPane.PLAIN_MESSAGE);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        setSize(700,650);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
