/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shortTermCourseManagement;

/**
 *
 * @author user
 */
import javax.swing.*;
import java.awt.*;
import java.time.format.DateTimeFormatter;
public class Tempframe extends javax.swing.JFrame {

    /**
     * Creates new form Tempframe
     */
    public JButton b1;
    public JTextField cname;
    public JTextField cfee;
    public JTextField cstdat;
    public JTextField cdurat;
    public JTextField crdept;
    public JTextField crdnam;
    public JTextField crdadd;
    public JTextField crdemail;
    public JTextField crdmob;
    public Course tempc;
    public Tempframe(JButton b1,Course tempc) {
        this.b1=b1;
        this.tempc=tempc;
        tempframe();
    }
    public void tempframe()
    {
        Container c=getContentPane();
        c.setLayout(new GridLayout(0,2));
        c.add(new JLabel("Course Name"));
        cname=new JTextField(tempc.courseName);
        c.add(cname);
        c.add(new JLabel("Course Fee"));
        cfee=new JTextField(Double.toString(tempc.courseFee));
        c.add(cfee);
        c.add(new JLabel("Course Startdate"));
        cstdat=new JTextField(tempc.initDate.format(DateTimeFormatter.ofPattern("dd-MM-uuuu")).toString());
        c.add(cstdat);
        c.add(new JLabel("Course duration"));
        cdurat=new JTextField(Integer.toString(tempc.durat));
        c.add(cdurat);
        c.add(new JLabel("Course Coordinator"));
        c.add(new JPanel());
        c.add(new JLabel("Coordinator deptt"));
        crdept=new JTextField(tempc.courseCoord.dept);
        c.add(crdept);
        c.add(new JLabel("Coordinator name"));
        crdnam=new JTextField(tempc.courseCoord.personName);
        c.add(crdnam);
        c.add(new JLabel("Coordinator address"));
        crdadd=new JTextField(tempc.courseCoord.personAddress);
        c.add(crdadd);
        c.add(new JLabel("Coordinator email"));
        crdemail=new JTextField(tempc.courseCoord.personEmail);
        c.add(crdemail);
        c.add(new JLabel("Coordinator mobile"));
        crdmob=new JTextField(Long.toString(tempc.courseCoord.personMobile));
        c.add(crdmob);
        c.add(new JPanel());
        c.add(b1);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(700,650);
        setVisible(true);
               
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
